### ISSUE TITLE
error running example shown in vignettes

### ISSUE THREAD

**Issue by olechnwin** [VilainLab/nanotatoR#15]
Hi,
I tried to run the main function shown in the vignettes but come across this error:
```
[1] "###Comparing SVs and Beds###"
Error in `[.data.frame`(r12, , 2) : undefined columns selected
```

I ran the following command which was copied from [nanotatoR vignettes](https://www.bioconductor.org/packages/release/bioc/vignettes/nanotatoR/inst/doc/nanotatoR.html) but changed terms to cancer:
```
terms <- "cancer"
gene <- gene_list_generation(
 method = "Single", term = terms,
 returnMethod = "dataFrame"
)
mergedFiles <- system.file ("extdata", "BNSOLO2_merged.txt", 
 package = "nanotatoR")
RzipFile = "zip.exe"
RZIPpath <- system.file("extdata", RzipFile, package = "nanotatoR")
smapName <- "F1.1_TestSample1_solo_hg19.smap"
smappath <- system.file("extdata", smapName, package = "nanotatoR")
path <- system.file("extdata", "SoloFile/", package = "nanotatoR")
hgpath <- system.file ("extdata", "GRCh37_hg19_variants_2016-05-15.txt", package = "nanotatoR")
decipherpath <- system.file("extdata", "population_cnv.txt", package = "nanotatoR")
bedFile <- system.file("extdata", "Homo_sapiens.Hg19.bed", package="nanotatoR")
pattern <- "_hg19.smap"
nanotatoR_main(smap = smappath, bed = bedFile,
 inputfmtBed = c("BNBED"),
 n = 3,  buildSVInternalDB = TRUE, soloPath = path, solopattern = pattern,
 input_fmt_INF = c("dataFrame"), buildBNInternalDB = FALSE,
 returnMethod_bedcomp = c("dataFrame"), returnMethod_DGV = c("dataFrame"),
 returnMethod_Internal = c("dataFrame"), input_fmt_DGV = c("dataFrame"),
 hgpath = hgpath, smapName = smapName, limsize=1000, win_indel_parents=5000,
 decipherpath = decipherpath, dbOutput_Int = "dataframe",
 win_inv_trans_parents=40000, win_indel_DGV = 10000,
 input_fmt_geneList = c("dataFrame"), input_fmt_svMap = c("dataFrame"),
 input_fmt_decipher = "dataFrame",input_fmt_BN = "dataFrame",
 returnMethod_GeneList = c("dataFrame"),returnMethod_BNCohort =  c("dataFrame"),
 returnMethod_decipher = c("dataFrame"), mergedFiles_BN = mergedFiles,
 dat_geneList = gene , method_entrez = "", 
 outpath = smappath, outputFilename = "test",
 RZIPpath = RZIPpath)
```
What was wrong with this?
Thank you.

**Comment by VilainLab** [comment]
Thanks for reporting this. There seems to be an issue, with the latest push. Will update this issue by the end of this week. Will update once we make the change.

Thanks again and keep providing us with your suggestions.

**Comment by VilainLab** [comment]
Hi,

We have changed the functionalities slightly and the latest version of the code can be downloaded from github.
library(devtools)
install_github("VilainLab/nanotatoR")
The code you can use to run is 
smapName="NA12878_DLE1_VAP_solo5.smap"
smap = system.file("extdata", smapName, package="nanotatoR")
bedFile <- system.file("extdata", "HomoSapienGRCH19_lift37.bed", package="nanotatoR")
hgpath=system.file("extdata", "GRCh37_hg19_variants_2016-05-15.txt", package="nanotatoR")
labelType = c("SE")
SE_path = system.file("extdata", "SoloFile/", package="nanotatoR")
SE_pattern = "*_DLE1_*"
Samplecodes = system.file("extdata", "nanotatoR_sample_codes.csv", package="nanotatoR")
mergeKey = system.file("extdata", "nanotatoR_control_sample_codes.csv", package="nanotatoR")
mergedKeyoutpath = system.file("extdata", package="nanotatoR")
mergedKeyFname = "Sample_index.csv"
RNASeqDir = system.file("extdata", "NA12878_P_Blood_S1.genes.results", package="nanotatoR")
path = system.file("extdata", "Bionano_config/", package = "nanotatoR")
pattern = "_hg19.txt"
outputFilename <- "NA12878_DLE1_VAP_solo5_out"
outpath <- system.file("extdata", smapName, package = "nanotatoR")
RZIPpath <- system.file("extdata", "zip.exe", package = "nanotatoR")
directoryName <- system.file("extdata", package="nanotatoR")
nanotatoR_main_Solo_SE(
    smap = smap, bed = bedFile, inputfmt = c("bed"), 
    n=3,
    buildBNInternalDB=TRUE,
    path = path , pattern = pattern, 
    buildSVInternalDB = TRUE,
    EnzymeType = c("SE"),
    labelType = c("SE"),
    SE_path = SE_path, SE_pattern = SE_pattern,
    win_indel_INF = 10000, win_inv_trans_INF = 50000, 
    perc_similarity_INF= 0.5, indelconf = 0.5, invconf = 0.01, 
    transconf = 0.1, 
    hgpath = hgpath, win_indel_DGV = 10000, win_inv_trans_DGV = 50000, 
    perc_similarity_DGV = 0.5,
    RNAseqcombo = TRUE,
    RNASeqDir = RNASeqDir, returnMethod = "dataFrame",
    pattern_Proband = "*_P_*",
    outpath = outpath, method_entrez = "Single", term = "Cancer",
    outputFilename = outputFilename, 
    termListPresent = TRUE,
    datGeneListPresent = FALSE,
    InternaldatabasePresent = FALSE,
    primaryGenesPresent = TRUE,
    fileprefix = "AnnotatedNA12878",
    directoryName = directoryName,
    outputType = c("csv"))

We are trying to push this to bioconductor by this cycle.

Again please let me know if this works, and provide us with comments about the tool.

Thanks,
Surajit
