### ISSUE TITLE
Using Nanotator with VCFs

### ISSUE THREAD

**Issue by oalavijeh** [VilainLab/nanotatoR#3]
Dear Nanotator team, 

I was looking to annotate a vcf file that is 1000 patients WGS SVs called by Manta and Canvas and then compare the results to a similarly merged vcf file of 17000 controls. 

Would your programme be able to do such a task? Can VCFs be fed into it or do they need to be customized at all? The current format is below:

CHROM POS ID REF ALT QUAL FILTER INFO FORMAT

1 2827693 MantaDEL:0:2:5000 CCGTGGATGCGGGGACCCGCATCCCCTCTCCCTTCACAGCTGAGTGACCCACATCCCCTCTCCCCTCGCA C . PASS SVTYPE=DEL;END=2827680;BKPTID=Pindel_LCS_D1099159;HOMLEN=1;HOMSEQ=C;SVLEN=-66 GT:GQ 1/1:13.9

2 321682 . T MantaBND:5:7:1:0 6 PASS IMPRECISE;SVTYPE=DEL;END=321887;SVLEN=-105;CIPOS=-56,20;CIEND=-10,62 GT:GQ 0/1:12

2 14477084 . C MantaINS:88:22:00:3 12 PASS IMPRECISE;SVTYPE=DEL;END=14477381;SVLEN=-297;MEINFO=AluYa5,5,307,+;CIPOS=-22,18;CIEND=-12,32 GT:GQ 0/1:12

3 9425916 . C MantaINS:5:333:000 23 PASS IMPRECISE;SVTYPE=INS;END=9425916;SVLEN=6027;CIPOS=-16,22;MIINFO=L1HS,1,6025,- GT:GQ 1/1:15

Many thanks for your time and I look forward to your reply. 

Omid

**Comment by VilainLab** [comment]
Thanks for the request..We would implement it soon....
