### ISSUE TITLE
nanotatoR hg38

### ISSUE THREAD

**Issue by RabeaW** [VilainLab/nanotatoR#5]
Hi,
I would like to use nanotatoR with my Bionano data (hg38). Based on the description of nanotatoR, I understand that it should be possible to use it with hg38 data. But in the extdata path only hg19 are located. Can you give me an advice how to use nanotatoR with hg38?
Thanks in advance,
Rabea

**Comment by VilainLab** [comment]
Really sorry for the late reply. There seemed to be some issue with github for which we were not getting any notification for the issue. Regarding your question the only places you need to think about hg38 is in the case of input data. So you have to provide the hg38 version for the DGV data, the BNDB datasets, the decipher datasets, and the bed file. We are in the process of updating our tutorial file currently. Once that is done woud update you.

If you face in locating any of the input files please let us know and we can help you regarding the same.

Thanks, 
Surajit

**Comment by RabeaW** [comment]
Dear Surajit,
Thank you for your reply.
Do I understand it correctly, that I need to provide the DGV data, the BNDB datasets, the decipher datasets, and the bed file? Or are you planning an update on this?
Just to make sure.
Thanks for clarification.
Best,
Rabea

Von: VilainLab <notifications@github.com>
Gesendet: Montag, 10. August 2020 23:41
An: VilainLab/nanotatoR <nanotatoR@noreply.github.com>
Cc: Wagener, Rabea - UKD <Rabea.Wagener@med.uni-duesseldorf.de>; Author <author@noreply.github.com>
Betreff: [Extern] - Re: [VilainLab/nanotatoR] nanotatoR hg38 (#5)


Really sorry for the late reply. There seemed to be some issue with github for which we were not getting any notification for the issue. Regarding your question the only places you need to think about hg38 is in the case of input data. So you have to provide the hg38 version for the DGV data, the BNDB datasets, the decipher datasets, and the bed file. We are in the process of updating our tutorial file currently. Once that is done woud update you.

If you face in locating any of the input files please let us know and we can help you regarding the same.

Thanks,
Surajit

-

**Comment by VilainLab** [comment]
Hi Rabea,

We currently have the latest bionano, OMIM,Clinvar, and decipher data in the following database https://github.com/VilainLab/nanotatoRexternalDB. We have a hg19 bed and the previous version of hg19 DGV database in the same database. We would update this database soon with hg38 bed and DGV files. You can download the hg38 dataset seperately from http://dgv.tcag.ca/dgv/docs/GRCh38_hg38_variants_2020-02-25.txt. For the bed you can d/l it directly from UCSC (https://genome.ucsc.edu/) or Gencode (ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_34/gencode.v34.annotation.gtf.gz). The following is the code we used to convert the gtf to bed file.
awk '{ if($3 == "gene" && $13 == "gene_status")   print $1,$4,$5,$16,$7  else if ($3 == "gene" && $13 == "gene_name")    print $1,$4,$5,$14,$7  }' gencode.v33.annotation.gtf >HomoSapienGRCH19.bed.

I have also updated the tutorial please let me know if you face any issue with the same.

Please let me know in case of any issues or concerns.

Thanks,
Surajit

**Comment by RabeaW** [comment]
Dear Surajit,
So I got it right. Ok. We can have a look at the data and can try if that works ☺ Other than that we will wait on your update. You have any idea when this update will be?
Best,
Rabea

Von: VilainLab <notifications@github.com>
Gesendet: Mittwoch, 12. August 2020 00:27
An: VilainLab/nanotatoR <nanotatoR@noreply.github.com>
Cc: Wagener, Rabea - UKD <Rabea.Wagener@med.uni-duesseldorf.de>; Author <author@noreply.github.com>
Betreff: [Extern] - Re: [VilainLab/nanotatoR] nanotatoR hg38 (#5)


Hi Rabea,

We currently have the latest bionano, OMIM,Clinvar, and decipher data in the following database https://github.com/VilainLab/nanotatoRexternalDB. We have a hg19 bed and the previous version of hg19 DGV database in the same database. We would update this database soon with hg38 bed and DGV files. You can download the hg38 dataset seperately from http://dgv.tcag.ca/dgv/docs/GRCh38_hg38_variants_2020-02-25.txt. For the bed you can d/l it directly from UCSC (https://genome.ucsc.edu/) or Gencode (ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_34/gencode.v34.annotation.gtf.gz). The following is the code we used to convert the gtf to bed file.
awk '{ if($3 == "gene" && $13 == "gene_status") print $1,$4,$5,$16,$7 else if ($3 == "gene" && $13 == "gene_name") print $1,$4,$5,$14,$7 }' gencode.v33.annotation.gtf >HomoSapienGRCH19.bed.

I have also updated the tutorial please let me know if you face any issue with the same.

Please let me know in case of any issues or concerns.

Thanks,
Surajit

**Comment by RabeaW** [comment]
Dear Surajit,
I just realized that only 332 genes are included in your Homo_sapiens.Hg19.bed file (mainly chr1, X and Y). Is this a mistake? I would prepare this as a genome-wide file…
Best,
Rabea

Von: VilainLab <notifications@github.com>
Gesendet: Mittwoch, 12. August 2020 00:27
An: VilainLab/nanotatoR <nanotatoR@noreply.github.com>
Cc: Wagener, Rabea - UKD <Rabea.Wagener@med.uni-duesseldorf.de>; Author <author@noreply.github.com>
Betreff: [Extern] - Re: [VilainLab/nanotatoR] nanotatoR hg38 (#5)


Hi Rabea,

We currently have the latest bionano, OMIM,Clinvar, and decipher data in the following database https://github.com/VilainLab/nanotatoRexternalDB. We have a hg19 bed and the previous version of hg19 DGV database in the same database. We would update this database soon with hg38 bed and DGV files. You can download the hg38 dataset seperately from http://dgv.tcag.ca/dgv/docs/GRCh38_hg38_variants_2020-02-25.txt. For the bed you can d/l it directly from UCSC (https://genome.ucsc.edu/) or Gencode (ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_34/gencode.v34.annotation.gtf.gz). The following is the code we used to convert the gtf to bed file.
awk '{ if($3 == "gene" && $13 == "gene_status") print $1,$4,$5,$16,$7 else if ($3 == "gene" && $13 == "gene_name") print $1,$4,$5,$14,$7 }' gencode.v33.annotation.gtf >HomoSapienGRCH19.bed.

I have also updated the tutorial please let me know if you face any issue with the same.

Please let me know in case of any issues or concerns.

Thanks,
Surajit

**Comment by VilainLab** [comment]
Hi Rabea,

Sorry for the late reply again. I think the file you are looking at is the bed file in the example of the tool.  We have a complete  hg19 bed file in the https://github.com/VilainLab/nanotatoRexternalDB folder and would upload the hg38 versions of the databases and bed file, by the end of this week,
Thanks,
Surajit

**Comment by RabeaW** [comment]
Dear Surajit,
Ah ok. Then I checked the wrong file. But when you upload everything until the end of the week, then I will wait for your files ☺
Thank you so much.
Best,
Rabea

Von: VilainLab <notifications@github.com>
Gesendet: Montag, 17. August 2020 17:12
An: VilainLab/nanotatoR <nanotatoR@noreply.github.com>
Cc: Wagener, Rabea - UKD <Rabea.Wagener@med.uni-duesseldorf.de>; Author <author@noreply.github.com>
Betreff: [Extern] - Re: [VilainLab/nanotatoR] nanotatoR hg38 (#5)


Hi Rabea,

Sorry for the late reply again. I think the file you are looking at is the bed file in the example of the tool. We have a complete hg19 bed file in the https://github.com/VilainLab/nanotatoRexternalDB folder and would upload the hg38 versions of the databases and bed file, by the end of this week,
Thanks,
Surajit
